bulletin/bulletin/bulletinapp/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from .views import *


app_name = 'bulletinapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('join/', JoinView.as_view(), name='join'),
    path('login/', LoginView.as_view(), name='login'),
    path('', MainView.as_view(), name='main'),
    path('my_page/', MyPageView.as_view(), name='my_page'),
    path('create/', CreateView.as_view(), name='create'),
    path('post/<int:post_id>/', ContentView.as_view(), name='post_content'),
    path('logout/', logout, name='logout'),
    path('my_page/my_post/', MyContentView.as_view(), name='my_post'),
    path('withdrawal/', account_withdrawal, name='withdrawal'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('change_info/<str:data>/', ChangeInfoView.as_view(), name='change_info'),
    path('update/<int:pk>/', UpdateView.as_view(), name='update'),
]

bulletin/bulletin/bulletinapp/templates/bulletinapp/change_info.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
        label{text-align:left}
        .form-control{margin:10px}
        .col-sm-3{margin-top:auto ; margin-bottom:auto}
        #user{color:var(--mainColor); display:inline-block}
        #ok{color:var(--mainColor)}
        #no{color:var(--errorColor)}
    </style>
    <title>Webpage</title>
</head>
<body class="container">
    <h1>MY PAGE</h1>
    <h2><div id="user">{{user.username}}</div>님, 환영합니다!</h2>
    <h3>개인정보 변경하기</h3>
    {% if ok_msg %}
        <h5 id="ok">{{ ok_msg }}</h5>
        <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">마이 페이지</button>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">변경</button>
            <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">다음에 변경하기</button>
        </form>
        {% if no_msg %}
            <br><h5 id="no">{{ no_msg }}</h5>
        {% endif %}
    {% endif %}
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/create.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Webpage</title>
    <meta charset="UTF-8">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Webpage</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        #users{display:inline-block ; color:var(--mainColor)}
        body{text-align:center ; font-family:'Do Hyeon',sans-serif;}
    </style>
</head>
<body>
    <br><header><h1>새 글 작성하기</h1></header><br>
    <div class="container">
        <div class="row">
            <div class="col-md"><h2><div id="users">{{ user.username }}</div>님, 환영합니다!</h2></div>
            <div class="col-md">
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:logout' %}">로그아웃</button>
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">마이페이지</button>
                <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000'">메인 페이지로</button>
            </div>
        </div>
    </div>
    <br><br><br>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.title.label }}
            <br>
            {{ form.title }}
            <br><br>
            {{ form.content.label }}
            <br>
            {{ form.content }}
        </div>
        <button type="submit" class="btn btn-primary">글 작성하기</button>
    </form><br>
    {{ ok_msg }}
    {{ no_msg }}
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/join.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Webpage</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        h1{text-align:center}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
        h5{color: var(--errorColor)}
    </style>
</head>
<body class="container">
    <h1>JOIN PAGE</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.id.label }}<br>
            {{ form.id }}
            <br><br>
            {{ form.password.label }}<br>
            {{ form.password }}
            <br><br>
            {{ form.password_confirm.label }}<br>
            {{ form.password_confirm }}
            <br><br>
            {{ form.username.label }}<br>
            {{ form.username }}
            <br><br>
            {{ form.email.label }}<br>
            {{ form.email }}
        </div><br>
        <button type="submit" class="btn btn-primary">회원가입</button>
        <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/'">시작 페이지로</button><br>
    </form>
    {% if msg %}
    <h5>{{ msg }}</h5>
    {% endif %}
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <title>Webpage</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        h1{text-align:center}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
    </style>
</head>
<body class="container">
    <form action="" method="post">
        <h1>LOGIN PAGE</h1>
        {% csrf_token %}
        {{ form }}
        <br>
        <br>
        <h5>{{ msg }}</h5>
        <button type="submit" class="btn btn-primary">로그인</button>
        <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/'">시작 페이지로</button>
    </form>
</body>
</html>


<!--


<div class="mb-3">
            <input type="text" class="form-control" name="id">
            <label class="form-label">User Id</label>
        </div>
        <div class="mb-3">
            <input type="text" class="form-control" name="password">
            <label class="form-label">Password</label>
        </div>


-->


bulletin/bulletin/bulletinapp/templates/bulletinapp/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Webpage</title>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        #users{color:var(--mainColor); display:inline-block}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
        .row{align-content: space-between}
    </style>
</head>
<body class="container">
    <header><h1>메인 페이지</h1></header>
    <div class="container">
        <div class="row">
            <div class="col-md"><h2><div id="users">{{ user.username }}</div>님, 환영합니다!</h2></div>
            <div class="col-md">
                <button type="button" class="btn btn-primary" onclick="location.href='logout'">로그아웃</button>
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">마이페이지</button>
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:create' %}">새 글 작성하기</button>
            </div>
        </div>
    </div>
    <br><br><br>
    {% if post_list %}
        <table class="table">
            <thead>
                <th scope="col">번호</th>
                <th scope="col">작성자</th>
                <th scope="col">제목</th>
                <th scope="col">작성일자</th>
            </thead>
            <tbody>
                {% for post in post_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ post.writer.username }}</td>
                    <td><a href="http://127.0.0.1:8000/post/{{ post.id }}">{{ post.title }}</a></td>
                    <td>{{ post.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>작성된 포스트가 없습니다.</p>
    {% endif %}
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/my_page.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Google Font code -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        h3{color:var(--errorColor)}
        #user{color:var(--mainColor); display:inline-block}
        body{font-family: 'Do Hyeon', sans-serif; text-align:center}
        .btn-toolbar{justify-content:center}
    </style>
    <!-- Bootstrap CSS -->
    <title>Webpage</title>
</head>
<body class="container">
    <h1>마이페이지</h1>
    <h2><div id="user">{{user.username}}</div>님, 환영합니다!</h2><br>
    {% if post_delete %}
    <h3>포스트가 삭제되었습니다.</h3>
    {% endif %}
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group me-2" role="group">
            <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/my_page/my_post/'">내가 쓴 글</button>
        </div>
        <div class="btn-group me-2" role="group">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">개인정보 변경</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="/change_info/password">비밀번호 변경</a></li>
                    <li><a class="dropdown-item" href="/change_info/username">이름 변경</a></li>
                    <li><a class="dropdown-item" href="/change_info/email">이메일 변경</a></li>
                </ul>
            </div>
        </div>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-danger" onclick="location.href={% url 'bulletinapp:withdrawal' %}">회원 탈퇴</button>
        </div>
    </div><br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/my_post.html
<!DOCTYPE html>
{% load static %}
{% load static %}
<html>
<head>
    <title>Webpage</title>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        #users{color:var(--mainColor); display:inline-block}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
        .row{align-content: space-between}
    </style>
</head>
<body class="container">
    <header><h1>내 포스트</h1></header>
    <div class="container">
        <div class="row">
            <div class="col-md"><h2><div id="users">{{ user.username }}</div>님, 환영합니다!</h2></div>
            <div class="col-md">
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:logout' %}">로그아웃</button>
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">마이페이지</button>
                <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:create' %}">새 글 작성하기</button>
            </div>
        </div>
    </div>
    <br><br><br>
    {% if post_list %}
        <table class="table">
            <thead>
                <th scope="col">번호</th>
                <th scope="col">작성자</th>
                <th scope="col">제목</th>
                <th scope="col">작성일자</th>
            </thead>
            <tbody>
                {% for post in post_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ post.writer.username }}</td>
                    <td><a href="{% url 'bulletinapp:post_content' post.id %}">{{ post.title }}</a></td>
                    <td>{{ post.date }}</td>
                    <td><button type="button" class="btn-close"></button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>아직 작성한 글이 없습니다.</p>
    {% endif %}
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/post_content.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <title>Webpage:post</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        body{font-family:'Do Hyeon',sans-serif;}
        h1, h2{text-align:center}
        .user{display:inline-block ; color:var(--mainColor)}
        #content{text-align:center}
    </style>
</head>
<body class="container">
    <br><header><h1>포스트 조회</h1></header><br>
    <div class="container">
        <div class="row">
            <div class="col-md"><h2><div class="user">{{ user.username }}</div>님, 환영합니다!</h2></div>
            <div class="col-md">
                <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/logout'">로그아웃</button>
                <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/my_page'">마이페이지</button>
                <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/'">메인 페이지로</button>
                {% if is_writer %}
                    <button type="button" class="btn btn-success" onclick="location.href='http://127.0.0.1:8000/update/{{ post.id }}'">글 수정하기</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='http://127.0.0.1:8000/delete/{{ post.id }}'">글 삭제하기</button>
                {% endif %}
            </div>
        </div>
    </div><br><br>
    <div class="d-grid gap-3">
        <div class="w-100 p-2 bg-light border">
            <label class="col-sm-2 col-form-label"><div class="user">제목</div></label>
            {{ post.title }}
        </div>
        <div class="w-100 p-2 bg-light border">
            <label class="col-sm-2 col-form-label"><div class="user">작성자</div></label>
            {{ post.writer.username }}
        </div>
        <div class="w-100 p-2 bg-light border">
            <label class="col-sm-2 col-form-label"><div class="user">작성일자</div></label>
            {{ post.date }}
        </div>
        <div class="w-100 p-2 bg-light border" id="content">
            {{ post.content|linebreaksbr }}
        </div>
    </div>
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/post_deleted.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <!-- Google Font code -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        h3{color:var(--errorColor)}
        #user{color:var(--mainColor); display:inline-block}
        body{font-family: 'Do Hyeon', sans-serif; text-align:center}
        .btn-toolbar{justify-content:center}
    </style>
    <!-- Bootstrap CSS -->
    <title>Webpage</title>
</head>
<body class="container">
    <h1>마이페이지</h1>
    <h2><div id="user">{{user.username}}</div>님, 환영합니다!</h2><br><br>
    <h3>포스트가 삭제되었습니다.</h3>
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group me-2" role="group">
            <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/my_page/my_post/'">내가 쓴 글</button>
        </div>
        <div class="btn-group me-2" role="group">
            <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/'">메인 페이지로</button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" onclick="location.href={% url 'bulletinapp:my_page' %}">마이 페이지로</button>
        </div>
    </div><br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/welcome.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <title>Webpage</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        div{height:200px}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
    </style>
</head>
<body class="container">
    <div></div>
    <h1>Webpage</h1>
    <button type="button" class="btn btn-primary" onclick="location.href='login'">로그인</button>
    <button type="button" class="btn btn-primary" onclick="location.href='join'">회원가입</button>
</body>
</html>

bulletin/bulletin/bulletinapp/templates/bulletinapp/withdrawal.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <title>Webpage</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        h1{text-align:center}
        h3{color: var(--errorColor)}
        body{text-align:center ; font-family: 'Do Hyeon', sans-serif;}
    </style>
</head>
<body class="container">
    <h1>RESIGN PAGE</h1>
    <br>
    {% if form %}
    <h2>정말 계정을 탈퇴하시겠습니까?</h2>
    <h3>현재 아이디와 비밀번호를 입력하고 '확인' 을 누르면 계정이 삭제됩니다.</h3>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-danger">계정 삭제</button>
        <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/my_page/'">마이 페이지로</button>
    </form>
    {% else %}
        {% if msg_ok %}
            <h2>{{ msg_ok }}</h2><br>
            <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/'">시작 화면으로</button>
        {% else %}
            <h2>{{ msg_no }}</h2>
            <button type="button" class="btn btn-primary" onclick="location.href='http://127.0.0.1:8000/my_page/'">마이 페이지로</button>
            <button type="button" class="btn btn-danger" onclick="location.href='http://127.0.0.1:8000/withdrawal/'">다시 입력하기</button>
        {% endif %}
    {% endif %}
</body>
</html>